apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonpakhru-content
  labels:
    app: sonpakhru-kubernetes
    app.kubernetes.io/name: sonpakhru-content
    app.kubernetes.io/instance: sonpakhru-kubernetes
    app.kubernetes.io/version: "5.92"
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: sonpakhru-kubernetes
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/apps/sonpakhru"
